#!/usr/bin/env python3
"""Write handbook.qmd from the lectures that exist, render it, and place the PDF.

The handbook binds every finished lecture body into one PDF with a course
glossary and index. Until all fourteen lectures exist, it includes only the
lectures whose `_body.qmd` is present, so the download is never broken.

Run from the repository root:

    python3 scripts/build_handbook.py            # write handbook.qmd and render
    python3 scripts/build_handbook.py --no-render

The rendered PDF is copied to the repository root as handbook.pdf, which the
site serves as a resource.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LECTURES = ROOT / "lectures"

TITLES = {
    "01": "From an Economic Question to a Local Projection",
    "02": "Levels, Differences, Cumulative Responses, and Units",
    "03": "Identification, Controls, and the Pre-Shock Information Set",
    "04": "LP-IV and Cumulative Multipliers",
    "05": "Pointwise Inference, Persistence, and Lag Augmentation",
    "06": "Inference About the Response Path",
    "07": "LPs versus VARs: Estimands, Bias, and Variance",
    "08": "Smoothing and Restrictions Across Horizons",
    "09": "State Dependence and Asymmetric Responses",
    "10": "What Linear LPs Mean in Nonlinear Economies",
    "11": "Panel LPs and Common Macroeconomic Shocks",
    "12": "LP Difference-in-Differences",
    "13": "Sensitivity Analysis and Policy Counterfactuals",
    "14": "Research Synthesis, Replication Audit, and Defense",
}


def latex_escape(text: str) -> str:
    return text.replace("&", r"\&").replace("%", r"\%")


def finished_lectures() -> list[tuple[str, Path]]:
    found = []
    for directory in sorted(LECTURES.glob("[0-9][0-9]-*")):
        number = directory.name[:2]
        if number in TITLES and (directory / "_body.qmd").is_file() and (directory / "glossary.qmd").is_file():
            found.append((number, directory))
    return found


def write_handbook(lectures: list[tuple[str, Path]], date: str) -> Path:
    numbers = [n for n, _ in lectures]
    if not numbers:
        sys.exit("no finished lecture found; nothing to bind")
    if len(numbers) == 1:
        span = f"Lecture {int(numbers[0])}"
    else:
        span = f"Lectures {int(numbers[0])}–{int(numbers[-1])}"
    bibs = "\n".join(f"  - lectures/{d.name}/references.bib" for _, d in lectures)

    parts = []
    for n, d in lectures:
        parts.append(
            "```{=latex}\n"
            f"\\part{{Lecture {int(n)} · {latex_escape(TITLES[n])}}}\n"
            "```\n\n"
            f"{{{{< include /lectures/{d.name}/_body.qmd >}}}}\n"
        )
    glossaries = []
    for i, (n, d) in enumerate(lectures):
        heading = f"Lecture {int(n)} terms" if i == 0 else f"Terms introduced in Lecture {int(n)}"
        glossaries.append(
            "```{=latex}\n"
            f"\\subsection*{{{heading}}}\n"
            "```\n\n"
            f"{{{{< include /lectures/{d.name}/glossary.qmd >}}}}\n"
        )

    text = f"""---
title: "Local Projections: From First Principles to Empirical Research"
subtitle: "Course handbook · {span}"
author: "Tyler Sotomayor"
date: {date}
date-format: "dddd, D MMMM YYYY"

# ————— chapter opener ————— (see lectures/_pdf/handbook.tex)
kicker: "Course handbook"
course: "Local Projections: From First Principles to Empirical Research"
strand: "Collected lectures"
contents-label: "Contents of this handbook"
contents-index: true
course-handbook: true

# Generated by scripts/build_handbook.py from the lectures that exist; edit
# that script, not this file. Each lecture is a part; sections restart at 1
# inside each one, so a lecture numbers the same here as in its standalone PDF.
number-sections: true
toc-depth: 3

fig-cap-location: top
link-citations: true

filters:
  - filters/course-apparatus.lua

format:
  pdf:
    documentclass: article
    fig-pos: H
    geometry:
      - letterpaper
      - top=1in
      - bottom=1in
      - left=1.15in
      - right=1in
      - headheight=14pt
    toc: false          # the contents strip is part of the opener instead
    colorlinks: true
    number-sections: true
    template-partials:
      - lectures/_pdf/title.tex
      - lectures/_pdf/before-body.tex
    include-in-header:
      - lectures/_pdf/handbook.tex
      - lectures/_pdf/handbook-parts.tex

bibliography:
{bibs}
csl: lectures/lp-apa.csl
---

{chr(10).join(parts)}
```{{=latex}}
\\clearpage
\\section*{{References}}
\\addcontentsline{{toc}}{{section}}{{References}}
```

::: {{#refs}}
:::

```{{=latex}}
\\clearpage
\\section*{{Course Glossary}}
\\addcontentsline{{toc}}{{section}}{{Course Glossary}}
\\markright{{Course Glossary}}
```

{chr(10).join(glossaries)}
```{{=latex}}
\\clearpage
\\markright{{Index}}
\\phantomsection
\\label{{course-index}}
\\printindex
```
"""
    path = ROOT / "handbook.qmd"
    path.write_text(text, encoding="utf-8")
    return path


def render() -> Path:
    # Rendering a single file inside a website project writes into the
    # project's output directory; the PDF is then copied to the root, which
    # the site serves as a resource.
    subprocess.run(["quarto", "render", "handbook.qmd"], cwd=ROOT, check=True)
    produced = ROOT / "_site" / "handbook.pdf"
    if not produced.is_file():
        produced = ROOT / "handbook.pdf"
    target = ROOT / "handbook.pdf"
    if produced != target:
        shutil.copyfile(produced, target)
    return target


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-render", action="store_true", help="write handbook.qmd only")
    parser.add_argument("--date", default=None, help="date for the opener (YYYY-MM-DD); default today")
    args = parser.parse_args()
    date = args.date
    if date is None:
        import datetime as _dt
        date = _dt.date.today().isoformat()
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", date):
        sys.exit("--date must be YYYY-MM-DD")

    lectures = finished_lectures()
    path = write_handbook(lectures, date)
    print(f"wrote {path.relative_to(ROOT)} with {len(lectures)} lecture(s): {', '.join(n for n, _ in lectures)}")
    if args.no_render:
        return 0
    pdf = render()
    print(f"rendered {pdf.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
